services:
  deepwater:
    #build: .
    image: rg.nl-ams.scw.cloud/quati/deepwater:latest
    ports:
      - "8800:8800"
    environment:
      - OCR_API_KEY=${OCR_API_KEY:-}
    restart: unless-stopped
