server:
  port: 8800
spring:
  cache:
    type: caffeine
    cache-names: base64-cache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=24h
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: deepwater
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: openhippo-catch-all
              uri: https://api.openhippo.io
              predicates:
                - Path=/**

model:
  vision: hippo-vision

ocr:
  api-key: your-api-key-here